spring:
  datasource:
    url: jdbc:h2:mem:whattoeat
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "dGVzdFNlY3JldEtleUZvckp3dFRlc3RpbmdQdXJwb3Nl"
  expiration: 86400000
  # 1000(밀리초) × 60(초) × 60(분) × 24(시간) = 24시간

kakao:
  map:
    rest-api-key: ${KAKAO_MAP_REST_API_KEY}
